name: List files

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: origin
      run: git remote show origin

    - name: FETCH_HEAD
      run: git diff --name-only FETCH_HEAD
    - name: origin/master
      run: git diff --name-only origin/master

    - name: Build clang-format docker
      run: cd .github/workflows && docker build --tag=linter .
    - name: Check clang-format
      run: docker run --rm --init -v $(pwd):/repo linter:latest clang-format --version
    - name: clang-format help
      run: docker run --rm --init -v $(pwd):/repo linter:latest clang-format --help

    - name: Check current commit
      run: docker run --rm --init -v $(pwd):/repo -w /repo linter:latest sh -c "git diff --name-only FETCH_HEAD | grep '\.c$\|\.h$\|\.cc$' | xargs clang-format --style=file --dry-run --Werror "
